### ISSUE TITLE
Double entry post replies 

### ISSUE THREAD

**Issue by Ignatious11** [stackernews/stacker.news#329] opened 2023-06-23 15:15 UTC
Using keyboard shortcut Ctrl + Enter creates a double entry on post replies as well as initial posts.

**Comment by ekzyis** [comment] 2023-06-23 15:16
Duplicate of #327. Fix is ready: #328

**Comment by ekzyis** [comment] 2023-06-23 15:16
But thanks for reporting!

**Closed by ekzyis** 2023-06-23 15:16 UTC
Labels: duplicate
