### ISSUE TITLE
Add Tor to local dev environment to test connecting to Tor-only nodes

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1155] opened 2024-05-07 17:00 UTC
I'm not sure the best way to do this, but we need to be able to attach tor-only nodes in local dev so we can better diagnose tor issues.

**Comment by riccardobl** [comment] 2024-10-29 14:31
is this a duplicate of https://github.com/stackernews/stacker.news/issues/1493 ?

**Comment by ekzyis** [comment] 2024-10-29 15:24
I think so yes, closing this one

**Closed by ekzyis** 2024-10-29 15:24 UTC
Labels: local dev, difficulty:medium, wallets, priority:high
