### ISSUE TITLE
Request: URL dupe detection to include Description posts in which that URL exists

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#150] opened 2022-05-04 22:17 UTC
If I am trying to do a Link Post but that link's URL exists in a Description post, I won't know that my post might be a duplicate.

For example, if I tried to do a Link post for: 
https://mail.stacker.news/subscription/form

I would not be notified that there is this post:

*Subscribe to SN's Saturday Newsletter*
https://stacker.news/items/25342

Might it even be useful to show possible dup posts where that URL is in the comments too?

**Comment by huumn** [comment] 2022-05-18 19:59
I'm not sure dupes is the place for this. 

The problem is that people shouldn't be posting links in the discussion area generally if they aren't also providing other valuable context.

Closing because I think this solution is "heavy," but I acknowledge the underlying problem.

**Closed by huumn** 2022-05-18 19:59 UTC
