### ISSUE TITLE
Add Top stacker, Top spender, Top cowboy to newsletter script

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#926] opened 2024-03-16 22:33 UTC
The script for the newsletter is in `scripts`.

https://stacker.news/items/467554

**Comment by SatsAllDay** [comment] 2024-03-22 00:41
Couple questions:
1. Should stackers in hiding be included in each category?
2. Top 5 for each?

**Comment by huumn** [comment] 2024-03-22 01:08
1. no
2. sure

:)

**Comment by SatsAllDay** [comment] 2024-03-22 01:55
While working on this, I think I uncovered a bug in the top spenders API response

<img width="561" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/cc2c33f8-edf5-4ef6-a613-9dfae904d47d">

Notice how Scoresby has spent more than grayruby but is listed below GR. Similarly, DarthCoin has spent more than davidw but is listed below him.

I think it's because of [this line](https://github.com/stackernews/stacker.news/blob/4b4a5361ef29fd0c51325a1e8a44d20b8195b019/api/resolvers/user.js#L60) in the User resolver.

Note that the switch case for spending in the resolver is `spent`, while the API request is using `spending` [here](https://github.com/stackernews/stacker.news/blob/4b4a5361ef29fd0c51325a1e8a44d20b8195b019/lib/constants.js#L48).

Should I fix this bug as part of this issue, or file it separately? A simple fix is likely as easy as adding another switch case to support `spending` mapping to the `spent` column.

**Comment by SatsAllDay** [comment] 2024-03-22 15:14
I confirmed the above issue is also happening in localhost, so I do believe it's a bug. I checked in the fix in the PR for this newsletter change, it was a simple one liner.

**Closed** 2024-03-23 17:23 UTC
Labels: enhancement, difficulty:easy
