### ISSUE TITLE
Withdraw does not recognize invoice prefixed with `lightning:`

### ISSUE THREAD

**Issue by DanGould** [stackernews/stacker.news#247] opened 2023-03-12 20:39 UTC
I'm not sure what url spec uses `lightning:` prefix, but a piece of software gave it to me as an invoice an it took some screwing around until I realized what the issue was. stacker.news just said it id not recognize / find a valid invoice

**Comment by cointastical** [comment] 2023-03-30 23:21
Duplicate of #148

**Closed** 2023-05-07 15:03 UTC
