### ISSUE TITLE
Rewards are not payed out consistenly

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#689] opened 2023-12-14 16:48 UTC
Seems like there was no ticket [for this](https://stacker.news/items/352241) yet. I searched for "rewards" on Github but found no ticket.

**Comment by huumn** [comment] 2023-12-14 17:23
Yeah this appears to be caused by us timing out waiting for a connection from prisma's connection pool. I'd guess the worker picked to run rewards is occasionally running other long running tasks. Both rewards and historical materialized views are both scheduled to run at exactly midnight.

**Comment by ekzyis** [comment] 2023-12-14 17:28
So solution might be to just add retry? I think you mentioned that to me once

**Comment by huumn** [comment] 2023-12-14 17:41
No need to randomize them. Just offset them so nothing that might take a long time runs at the same time.

We can't retry rewards as-is. They aren't atomic.

**Comment by ekzyis** [comment] 2023-12-14 18:06
> No need to randomize them. Just offset them so nothing that might take a long time runs at the same time.

Also good idea. I forgot that we don't have the exact same situation here. At my previous position, I had the idea to randomize since we never knew when our servers are going to get hit by a huge wave of automated abuse reports, not realizing they are actually DDOSing our servers, lol

> We can't retry rewards as-is. They aren't atomic.

Oh, right, that would be a bad idea, lol

**Comment by huumn** [comment] 2023-12-21 23:56
This specific issue should be fixed in 628f755afd33f7d31ca34d8a585e0ade5935d0e9

**Closed by huumn** 2023-12-21 23:56 UTC
Labels: bug
